version: "3.9"

services:

  admin:
    build: ./mrmpg-admin
    container_name: admin-app
    ports:
      - "4174:4173"

  backend:
    build: ./mrmpg-backend
    container_name: backend-app
    ports:
      - "5000:5000"

  member:
    build: ./mrmpg-member
    container_name: member-app
    ports:
      - "4173:4173"

  user:
    build: ./mrmpg-user
    container_name: user-app
    ports:
      - "4175:4173"
